package slogdiscord

import (
	"fmt"
	"log/slog"
	"time"
)

// DiscordEmbed is the structure Discord expects for an embed message.
type DiscordEmbed struct {
	Title       string       `json:"title,omitempty"`
	Description string       `json:"description,omitempty"`
	Color       int          `json:"color,omitempty"`
	Timestamp   string       `json:"timestamp,omitempty"`
	Fields      []EmbedField `json:"fields,omitempty"`
	Footer      *EmbedFooter `json:"footer,omitempty"`
}

// EmbedField represents the name-value pairs in the embed.
type EmbedField struct {
	Name   string `json:"name"`
	Value  string `json:"value"`
	Inline bool   `json:"inline"`
}

// EmbedFooter represents optional footer text in the embed.
type EmbedFooter struct {
	Text string `json:"text,omitempty"`
}

// LevelColors is a map that lets you customize colors for each log level.
// For example: "INFO": 0x3498db, "ERROR": 0xe74c3c, etc.
type LevelColors map[string]int

// Default colors for known log levels if user does not provide them
var defaultColors = map[string]int{
	"DEBUG": 0x95a5a6, // Gray
	"INFO":  0x3498db, // Blue
	"WARN":  0xf1c40f, // Yellow
	"ERROR": 0xe74c3c, // Red
}

// DefaultEmbed is the fallback converter if the user doesn't provide a CustomEmbed.
// It uses the LevelColors map for color-coding, plus some default formatting for title/description.
func DefaultEmbed(r slog.Record, levelColors LevelColors) *DiscordEmbed {
	// Convert slog attrs to fields
	fields := []EmbedField{}
	r.Attrs(func(a slog.Attr) bool {
		fields = append(fields, EmbedField{
			Name:   a.Key,
			Value:  fmt.Sprintf("%v", a.Value),
			Inline: true,
		})
		return true
	})

	levelStr := r.Level.String()

	// Use custom color if provided, else fallback to the defaults
	color := defaultColors[levelStr]
	if custom, ok := levelColors[levelStr]; ok {
		color = custom
	}

	return &DiscordEmbed{
		Title:       fmt.Sprintf("[%s] %s", r.Time.Format(time.RFC3339), levelStr),
		Description: "Log message details:",
		Color:       color,
		Fields:      fields,
		Footer: &EmbedFooter{
			Text: "Generated by slog-discord",
		},
		Timestamp: r.Time.Format(time.RFC3339),
	}
}
